### ISSUE TITLE
A new HAR-viewer

### ISSUE THREAD

**Issue by soulgalore** [sitespeedio/har#1]
Been looking for a new HAR-viewer for some time haven't found one. Today we use a [forked version](https://github.com/sitespeedio/simplehar) of simplehar but it uses JQuery and Bootstrap to create the HAR, we would want to have the viewer as clean as possible.

I really like the viewer in WebPageTest because I usually can spot problems in it pretty fast, I think that is one most important things. 

Been thinking a lot on what would make a good HAR viewer, here are some bullets up for discussion: 

* Open Source (would be cool if it's so good that many projects use it) 
* SVG (best thing I've seen is the resource waterfall if the [performance bookmarklet](https://github.com/micmro/performance-bookmarklet)  
* Clean separation of model & view.
* Coloring: I think it would be great if all tools have the colors, so we should aim to have the same colors as WebPageTest. What's cool in WebPageTest is that you can color either by content type or have the bar split in different colors depending on timings. I personally like color by content type with the ability to switch.
* How to fit a large waterfall? One of the problems is how to show what's necessary for us to understand what asset we showing and still have some space left to show the waterfall.I'm not 100% sure there what's the best.
* In sitespeed.io we render the pages once and run them without a server, so it would be cool if we could prerender the pages that show the waterfall (meaning both functionalities to load the HAR using JS and render it in nodejs).
* The possibility to compare HAR files. WebPageTest is doing but by changing the opacity on different layers is that the way to go or are there other ways?
* One thing I like with the current modified version we use is that we have the ability to run some super simple rules on an asset, so that we can highlight if something is wrong (like missing cache headers). It looks like this: 
<img width="429" alt="screen shot 2015-12-14 at 09 41 27" src="https://cloud.githubusercontent.com/assets/540757/11776380/eba21276-a246-11e5-93c0-b1ccd335374b.png">
* We should show every timing in the timings field in the HAR (also those that starts with an underscore) so we can show cool things like start render etc.

Well this is just a start :)

**Comment by hmil** [comment]
This is something the internet very much needs. Also:
- minimalist and modular unlike [harviewer](https://github.com/janodvarko/harviewer). To make embedding easier and allow easy extension for a wide range of usages.
- permissive license unlike unlike [simplehar](https://github.com/rafacesar/simplehar). To benefit from all sorts of contributions, not just open-source projects.

**Comment by soulgalore** [comment]
Hi @hmil ,
yes I agreee. We have started to use https://github.com/micmro/PerfCascade 
Best
Peter
